# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HouseFinder2
                                 A QGIS plugin
 This plugin search houses
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-20
        copyright            : (C) 2024 by Ilia Novikov
        email                : ilia.p.novikov@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HouseFinder2 class from file HouseFinder2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .house_finder2 import HouseFinder2
    return HouseFinder2(iface)
